version: "3"
services:
  webserver:
    build:
      context: ./nginx
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./yeet:/var/www/vhosts/yeet
    depends_on:   
      - yeetapp
      - yeetdb
      # - yeetbot
    networks:
      - yeetnet
  yeetdb:
    image: mysql
    container_name: yeetdb
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=yeetdb"
      - "MYSQL_USER=yeet_user"
      - "MYSQL_PASSWORD=yeet_password"
      - "MYSQL_ROOT_PASSWORD=yeet_password"
    networks:
      - yeetnet
  # yeetbot:
  #   container_name: yeetbot
  #   build:
  #     context: ./yeetbot
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./yeetbot/:/yeetbot
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - yeetapp
  #   networks:
  #     - yeetnet
  yeetapp:
    build:
      context: ./yeet
      dockerfile: Dockerfile
    container_name: yeetapp
    volumes:
      - ./yeet:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - yeetnet
networks:
  yeetnet:
    driver: bridge
