version: "3"
services:
  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./yeet:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:   
      - yeetapp
      - yeetdb
      - yeetbot
    networks:
      - yeetnet
  yeetdb:
    image: mysql
    container_name: yeetdb
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=yeetdb"
      - "MYSQL_USER=yeet_user"
      - "MYSQL_PASSWORD=yeet_password"
      - "MYSQL_ROOT_PASSWORD=yeet_password"
    networks:
      - yeetnet
  yeetbot:
    container_name: yeetbot
    build:
      context: ./yeetbot
      dockerfile: Dockerfile
    volumes:
      - ./yeetbot/:/yeetbot
    depends_on:
      - yeetapp
    networks:
      - yeetnet
  yeetapp:
    build:
      context: ./yeet
      dockerfile: Dockerfile
    container_name: yeetapp
    volumes:
      - ./yeet:/var/www/html
    ports:
      - "8001:9000"
    networks:
      - yeetnet
networks:
  yeetnet:
    driver: bridge
