version: "3"
services:
  webserver:
    build:
      context: ./nginx
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./yeet:/var/www/vhosts/yeet
      - ./yeetbot:/var/www/vhosts/yeetbot
      - ./certbot:/var/www/certbot
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    depends_on:   
      - yeetapp
      - yeetdb
    networks:
      - yeetnet
  yeetdb:
    image: mysql
    container_name: yeetdb
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=yeetdb"
      - "MYSQL_USER=yeet_user"
      - "MYSQL_PASSWORD=yeet_password"
      - "MYSQL_ROOT_PASSWORD=yeet_password"
    networks:
      - yeetnet
  yeetbot:
    container_name: yeetbot
    build:
     context: ./yeetbot
     dockerfile: Dockerfile
    volumes:
     - ./yeetbot:/yeetbot
    depends_on:
     - webserver
    ports:
      - "5000:5000"
    networks:
     - yeetnet
  yeetapp:
    build:
      context: ./yeet
      dockerfile: Dockerfile
    container_name: yeetapp
    volumes:
      - ./yeet:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - yeetnet
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot:/var/www/certbot
  #     - ./certbot-etc:/etc/letsencrypt
  #     - ./certbot-var:/var/lib/letsencrypt
  #     - ./yeet:/var/www/vhosts/yeet
  #   depends_on:
  #     - webserver
  #   networks:
  #     - yeetnet
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email olamileke.dev@gmail.com --agree-tos --no-eff-email --force-renewal -d theyeetapp.com
networks:
  yeetnet:
    driver: bridge
